spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/craftconnect
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
razorpay.key.id=rzp_test_T2pn1rYGirclVN
razorpay.key.secret=cxv2rTuIaLBWoiIPS7Jo3zaS
cloudinary.cloud-name=dzchtn81j
cloudinary.api-key=232154444255473
cloudinary.api-secret=jKXEeloktenwdy7h9OEmvMMzlLU